### PR TITLE
First Pull request

### PR DESCRIPTION
**Pull request by algerina**
Changes made in this pull request:
- Creating an HTML page with Hello Microverse header.
- Styling using CSS.
- Adding a new Branch.
- Setting Linters configuration.
- Fixing indentation in HTML document.

### CODE REVIEW

**Review by safafa — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUESTED ♻️ 

Hi @algerina, You did a great job so far 👏🏼 👏🏼 

- The linters are correctly set and all the checks are passing.
- Well done on using the Microverse Readme Template.
- The commit messages are descriptive.
- Gitflow is correctly used

However, you still have to work on one point to get your project approved.

## Required changes :

- [ ] Pull Request comment should have a short summary describing introduced changes in more detail. 
Like for example :  
In this Pull requested I made the following changes : 
- Linters configuration
-  Creating Html page with a Hello Microverse header and styled it using CSS 


## Optional changes :
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- Adding a project screenshot in the Readme file. It gives an idea of how your project looks like and it makes the Readme file more descriptive

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by algerina** [comment]
Done, thanks for your review.

**Review by ahmetbozaci — APPROVED** [review]
# STATUS: Approved  🥳   🎉🎉🎉

### Hello @algerina  ✋🏼 Nice done with working on last review. I am impressed. Your project is great. I approve it. There is nothing else to say other than... it's time to merge it and delete the branch. You can submit this project in your dashboard.

### Cheers and Happy coding! 💻 👏
aproved


___
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form.](https://airtable.com/shrQAqnBwek5a0O0s)_
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [ahmetbozaci](https://github.com/ahmetbozaci), I will receive a notification and will respond._

[GitHub](https://github.com/ahmetbozaci) | [LinkedIn](https://linkedin.com/in/ahmetbozaci) | [Twitter](https://twitter.com/ahmtbozaci)

_Reviewed by [Ahmet Bozacı ](https://github.com/ahmetbozaci)_

**Comment by algerina** [comment]
@ahmetbozaci Thank you.

**Pull request merged**
